### ISSUE TITLE
what the usage of PclmWriter?

### ISSUE THREAD

**Issue by wwwqyhme** [HPInc/jipp#106]
I want to use ipp to print a pdf,but the printer do not support `application/pdf` format 

it support:

``` 
formats = {ArrayList@13613}  size = 6
 0 = "application/vnd.hp-PCL"
 1 = "image/jpeg"
 2 = "image/urf"
 3 = "image/pwg-raster"
 4 = "application/PCLm"
 5 = "application/octet-stream"
```

so, how can I print a pdf ? can I use PclmWriter to convert a pdf file to pclm file ?

**Comment by GladeDiviney** [comment]
That is correct; convert it and then send using PCLm or PWG-Raster.
