### ISSUE TITLE
Where can I set the paper size?（HP and Canon tests）

### ISSUE THREAD

**Issue by DevenLiang** [HPInc/jipp#111]
Initiating a print task on the HP printer runs normally, but when the Canon printer initiates a print task, it says no paper has been placed. Do I need to set the paper size for this situation? Where can I set the paper size?

![image](https://user-images.githubusercontent.com/20750469/123091272-ba70d000-d45b-11eb-9ef7-0d5924f6c04a.png)

**Comment by DevenLiang** [comment]
Test it on Android

**Comment by GladeDiviney** [comment]
Add a [MediaCol](https://github.com/HPInc/jipp/blob/55c96b76a3fb30ef00772813412015f5edd2cfbf/jipp-core/src/main/java/com/hp/jipp/model/MediaCol.kt) to your job attributes.

**Comment by DevenLiang** [comment]
Hi，What properties MediaCol needs to set for the option to specify cartons and print standard A4 paper？

**Comment by DevenLiang** [comment]
> Add a [MediaCol](https://github.com/HPInc/jipp/blob/55c96b76a3fb30ef00772813412015f5edd2cfbf/jipp-core/src/main/java/com/hp/jipp/model/MediaCol.kt) to your job attributes.

Hi，What properties MediaCol needs to set for the option to specify cartons and print standard A4 paper？

**Comment by GladeDiviney** [comment]
Good question! You can learn more about how to use `media-col` in [PWG-5100.7](https://ftp.pwg.org/pub/pwg/candidates/cs-ippjobext20-20190816-5100.7.pdf). Consider querying your printer's `media-col-database` or other attributes to see what it supports.

**Comment by DevenLiang** [comment]
Thanks. Let me take a closer look at the properties supported by my printer and see if I can find a solution.

**Comment by DevenLiang** [comment]
Thank you very much, my problem has been solved!
