### ISSUE TITLE
About the picture format printing problem

### ISSUE THREAD

**Issue by DevenLiang** [HPInc/jipp#115]
The printing format is set to image/jpeg. When the printing task was started, the printer received error 853. The machine used was a Canon printer, but for some reason it failed. PDF format can be printed normally.Do I need any special Settings for this picture?

**Comment by DevenLiang** [comment]
On the HP printer, the image/jpeg format was set to initiate the printing task, which was also unsuccessful, and the printer received no feedback. But the interface returns SUCCESS -OK. Is there a missing setting?

**Comment by GladeDiviney** [comment]
Hi @DevenLiang, this issue list is for issues with JIPP, not specific printers. Do you have a question about JIPP?

**Comment by DevenLiang** [comment]
Types.documentformat. of("image/ JPEG ") cannot print the image format properly when I use JIIP.
![image](https://user-images.githubusercontent.com/20750469/126604005-6b576084-ef60-46ed-a95c-f41a9186fe17.png)

**Comment by DevenLiang** [comment]
> Hi @DevenLiang, this issue list is for issues with JIPP, not specific printers. Do you have a question about JIPP?

Types.documentformat. of("image/ JPEG ") cannot print the image format properly when I use JIIP.

![image](https://user-images.githubusercontent.com/20750469/126604220-91c73a9b-af40-457a-954d-573162e843a6.png)

**Comment by GladeDiviney** [comment]
It's up to the printer to accept or reject requests. And not all printers support all document formats. You may need to request printer attributes before sending image/jpeg:

```kotlin
        // Query for supported document formats
        IppPacket attributeRequest = IppPacket.getPrinterAttributes(uri)
                .putOperationAttributes(
                        requestingUserName.of(CMD_NAME),
                        requestedAttributes.of(documentFormatSupported.getName()))
                .build();
```

Best of luck with your project.
