### ISSUE TITLE
Scanning document

### ISSUE THREAD

**Issue by artem24630** [HPInc/jipp#116]
Is it possible to scan documents or xeroxing them with your library?

**Comment by GladeDiviney** [comment]
In theory at least.

IPP includes scanning capabilities (http://ftp.pwg.org/pub/pwg/candidates/cs-ippscan10-20140918-5100.17.pdf), and JIPP could use those operations and attributes.

But at present, most printers implement different scanning protocols that JIPP doesn't support.
