### ISSUE TITLE
responseCode 500

### ISSUE THREAD

**Issue by 19940610mxh666** [HPInc/jipp#117]
When I used default print Settings on ubuntu system, added printer with IPP, PDD file with IPP everywhere, test Page printed successfully. When I use jipp, jprint returns responseCode 500.What's the difference between the two ways, Jipp and cups?

**Comment by GladeDiviney** [comment]
There are lots of differences but they implement parts of the same specifications.

You got a 500 because you sent data to the printer it didn't expect. If you post the code or the exchange, we may be able to help.

**Comment by 19940610mxh666** [comment]
thanks for your help
