### ISSUE TITLE
How to choose tray of the printer?

### ISSUE THREAD

**Issue by artem24630** [HPInc/jipp#119]
I need to print using the second tray if the first is empty, and printer can do this itself but not it doesn't (maybe I don't write some params to ipp request?). And  I tried to choose a tray by  writing `putOperationAttributes(MediaCol.mediaSource.of("tray-2"))` but it doesn't work. How to cope with it?

**Comment by teemoo7** [comment]
Hello,
Did you try to set this attribute to the job instead of the operation?

Example:
```java
MediaCol mediaCollection = new MediaCol();
		mediaCollection.setMediaSource(new KeywordOrName(MediaSource.bottom));

IppPacket printRequest = IppPacket.printJob(uri)
	.putOperationAttributes(documentFormat.of("application/pdf"), pageRanges.of(new IntRange(1, 1)))
	.putJobAttributes(mediaCol.of(mediaCollection)).build();
```
I think it worked for me.
Cheers
