### ISSUE TITLE
Not a Java implementation of IPP 

### ISSUE THREAD

**Issue by nikitasius** [HPInc/jipp#132]
Folks, let's be clear.

**Comment by GladeDiviney** [comment]
It's written in Kotlin. Where do you see a claim it is written in Java?

**Comment by nikitasius** [comment]
![image](https://user-images.githubusercontent.com/3670331/205707399-8a62667a-92ff-4b83-b9a4-7f625434aaac.png)
here is it

**Comment by GladeDiviney** [comment]
Thank you, this is fixed.
