### ISSUE TITLE
output-device-uuid operation attribute not deserialized 

### ISSUE THREAD

**Issue by jakekaplow** [HPInc/jipp#134]
- send request with `output-device-uuid` set
- print `packet[Tag.operationAttributes].get[Types.outputDeviceUuid)`

expected:
- the value in the request

actual:
- null

**Comment by HPSudip** [comment]
Thanks @jakekaplow , as discussed, we will look into it, please share if you have any logs of the incoming packet supporting this issue.

**Comment by HPSudip** [comment]
As per the code it should work if the incoming request should have the uuid set as valid java.net.URI. For example 
`urn:uuid:f81d4fae-7dec-11d0-a765-00a0c91e6bf6`  as per https://www.rfc-editor.org/rfc/rfc4122.

Can you please confirm that?

Also to get a value from a group tag, we can use `packet.getValue(Tag.operationAttributes, Types.outputDeviceUuid)`

**Comment by jakekaplow** [comment]
Thanks @HPSudip, I was sending the URI incorrectly.
