### ISSUE TITLE
How to add 'PageOrderReceived' job attribute? 

### ISSUE THREAD

**Issue by xiafengyujialing** [HPInc/jipp#141]
使用双面打印的时候，因为A4纸张一面有logo且放入抽拉纸盒中以logo面朝下的固定方向，想通过页码逆序的方式打印，这样和单面打印出来的面保持一致。

**Comment by HPSudip** [comment]
JIPP don't support obsolete attributes. This attribute is obsolete as per https://ftp.pwg.org/pub/pwg/candidates/cs-ippppx20-20230131-5100.3.pdf.

**Comment by xiafengyujialing** [comment]
收到您的邮件
