### ISSUE TITLE
How to set IppPacket version number in Java

### ISSUE THREAD

**Issue by agogala** [HPInc/jipp#147]
I'm trying to set `IppPacket` version number to `0x100` in java. It would seem there are two Kotlin methods with same signature and therefore this can not be done in Java.

Code is based in jprint example

```java
        IppPacket.Builder builder = IppPacket
            .getPrinterAttributes(uri)
            .putOperationAttributes(requestingUserName.of(CMD_NAME), requested);
        builder.setVersionNumber(0x100);
```

![setVersionNumberInJava](https://github.com/HPInc/jipp/assets/22502163/e928a41f-a5a5-47e6-9a0b-c9f909f58282)

I'm using version 0.7.14 of jipp-core.

**Comment by HPSudip** [comment]
It seems, we need to put `@set:JvmSynthetic` in the Kotlin code for these variables so that Java can only see and call the builder setters.
