### ISSUE TITLE
Batch-import fields from IANA

### ISSUE THREAD

**Issue by GladeDiviney** [HPInc/jipp#15]
Write a script to convert https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xhtml to appropriate .kt files.

**Comment by wifiprintguy** [comment]
You might rather want to target the XML version: https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml

That document is structured to isolate the different sub-registries within their own parent grouping elements. That may make the implementation easier than parsing HTML.

**Comment by GladeDiviney** [comment]
Excellent point!

**Comment by GladeDiviney** [comment]
Completed in 0.6 branch.
