### ISSUE TITLE
LaserJet Enterprise M407[client-error-bad-request]

### ISSUE THREAD

**Issue by queal** [HPInc/jipp#165]
I submitted a print job through IPP to the printer.
ippRequestPackage like this:

```
IppPacket(v=0x200, c=Print-Job(2), r=0x1) {
 operation-attributes {
  attributes-charset = utf-8,
  attributes-natural-language = en-us,
  printer-uri = http://192.168.6.43:631/ipp/print,
  requesting-user-name = "tms" (name),
  document-format = image/pwg-raster },
 printer-attributes { media-supported = iso_a4 } 
}
```

LaserJet Enterprise M407 Resp like this:
```
IppPacket(v=0x200, c=client-error-bad-request(1024), r=0x1) { 
attributes-charset = "utf-8" (charset),  attributes-natural-language = "en" (naturalLanguage) 
} 
```

LaserJet MFP M232dw is ok

I sought assistance from HP customer service, but I didn't receive any useful support.
I now understand that a certain attribute in IPP is missing. How should I handle this? I have tried everything, so I came here to ask for help.

My English is not very good, and I used ChatGPT for translation. I hope you understand.

tks for everyone

**Comment by queal** [comment]
@HPNavjot

**Comment by HPNavjot** [comment]
@queal you can refer to [IPP registrations](https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xhtml) and [RFC-8011](https://www.rfc-editor.org/rfc/rfc8011.html#section-4.2.1) these documents provide information on attributes and values for all the operations allowed via IPP protocol.

**Comment by HPNavjot** [comment]
can you try removing the printer-attributes from the print-job request, as it is not a valid attribute group for print -job request. 
refer: https://www.rfc-editor.org/rfc/rfc8011.html#section-4.2.1.1

**Comment by queal** [comment]
removing the printer-attributes is ok!!!! thks!!!!
