### ISSUE TITLE
Support Wi-Fi Direct Printing

### ISSUE THREAD

**Issue by nowavewater** [HPInc/jipp#27]
Does this library compatible with Wi-Fi Direct Printing? If yes. could you provide more examples?

**Comment by GladeDiviney** [comment]
Yes, it is compatible with Wi-Fi Direct Printing such as specified in the Wi-Fi Peer-to-Peer Services Print Technical Specification. That specification refers to certain IPP attributes, all of which are supported by JIPP.

PDLs (page description languages) are trickier, there are many border cases in PCLm and PWG-Raster that are not supported very well by JIPP yet.

For a quick sample look in `sample/jprint` in this repo.
