### ISSUE TITLE
Allow multiple values only for 1-set-of types

### ISSUE THREAD

**Issue by GladeDiviney** [HPInc/jipp#29]
Currently all `AttributeType` and `Attribute` objects support the storage of multiple values. This is not as per specification, since some items can be sets and others cannot. This encourages specification violations by allowing users to supply multiple values for an attribute type that doesn't support them.

To address this we would need separate types for single-value attributes (which could contain 0 or 1 values) and multi-value attributes (containing an ordered collection of 0 to `n` values, confusingly called "1setOf" in IPP specifications).

**Comment by wifiprintguy** [comment]
I don't believe it is OK for a single-value attribute to have "zero values". Instead of there being an absence of a value, one of the IPP "out-of-band values" (https://tools.ietf.org/html/rfc8011#section-5.1.1) should be present instead, if the attribute's syntax allows it.

**Comment by GladeDiviney** [comment]
In cases where there are 0 values of the defined type I consider it an "empty" attribute, but of course as you say in this case it needs an out-of-band tag, e.g.:

```
Types.mediaDefault.empty(Tag.notSettable)
```

I considered whether the "empty" case be defined for all attributes. After all, the IPP registrations page defines specific cases where e.g. `no-value` is acceptable. But are other cases (such as a response to Set-Printer-Attribute) that aren't attribute-specific. So to be safe it looks like we need to allow an empty attribute for all attribute types.

**Comment by GladeDiviney** [comment]
To enforce this with Java's type system would require two forms of every attribute type: `BooleanType`, `BooleanSetType`, so that for a non-set type you can `Types.colorSupported.of(true)` but not `Types.colorSupported.of(true, false)`. That's a lot of new types for a small benefit.

Another way to do this would be to offer static methods on a new `Attr` class:

```
Types.colorSupported.of(true)  // old and busted
Attr.colorSupported(true)  // new hotness
```

This approach would require:
* Methods defined for each type in `Types` according to their setness. (varargs only present for 1setOf types)
* Overrides for special cases like IntOrIntRange which can accept multiple types
* Accept varargs of the base type(s) only, such as `Int`, `IntRange`, `IntOrIntRange`. For more specialized combinations with Iterable types, fall back to `Types.printSpeedSupported.ofIntegers(...)`.
* An `Attr` class with with about 1000 static methods (to cover 834 types, 91 of which have `Or`-style types)
