### ISSUE TITLE
How to transform a PDF to PCLm?

### ISSUE THREAD

**Issue by aaaristo** [HPInc/jipp#53]
The sample code seems not to make use of any transformation.

Is there a way to update it to show how to create a RenderableDocument from a PDF?

**Comment by GladeDiviney** [comment]
You will need to integrate a PDF renderer for that (such as PdfBox, or other platform-specific APIs) and use its page iteration and rendering capabilities to generate RenderablePage objects to rasterize different parts of the page.

**Comment by GladeDiviney** [comment]
A sample showing how to do this would be helpful!

**Comment by GladeDiviney** [comment]
Fixed in #61, thanks @psoreide

**Comment by kangear** [comment]
Pdf -> bitmap -> pclm, it will take too long time. almost 40S.

**Comment by GladeDiviney** [comment]
Is this a problem with PDFBox or something in JIPP-PDL?
