### ISSUE TITLE
Printer prints hundreds of pages with wired chars

### ISSUE THREAD

**Issue by 39otrebla** [HPInc/jipp#66]
I'm trying to print [this simple PDF document](https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf) from Android using this library, using my Epson Workforce 3520 via Wi-Fi Direct.

I'm connected to the printer and able to send documents to print. However, it's happening something really strange. Instead of printing one copy of my PDF, the printer is throwing out hundreds of pages with wired chars. They seem small chunks of data, and they get printed one for each page. The printer is definitively not interpreting the file I'm sending correctly.

Here is the code:

```java
final File file = new File(mContext.getFilesDir(), filename);

URI uri = URI.create("http://192.168.10.1:631/ipp/print");

IppPacket printRequest = new IppPacket(Operation.printJob, 125, AttributeGroup.groupOf(Tag.operationAttributes, printerUri.of(uri)));

IppClientTransport transport = new HttpIppClientTransport();
try {
    IppPacketData request = new IppPacketData(printRequest, new FileInputStream(file));
    IppPacketData response = transport.sendData(uri, request);
    
    Log.d("main", response.getPacket().prettyPrint(100, "  "));
} catch (IOException ex) {
    Log.e("main", "Error: "+ ex.toString());
}
```

I've already tried sending `documentFormat` as `application/octet-stream` but nothing. Also tried `text/plain` and `application/pdf`, but I got `document-format-not-supported` error.

Also, I get the same strange behavior printing from `jprint` sample application from this repo.

**Comment by GladeDiviney** [comment]
Your printer likely does not support PDF. See https://github.com/HPInc/jipp/issues/64#issuecomment-516514784.

It would be good if jprint checked for this before printing anything! Leaving this issue open to at least prevent that much.

**Comment by 39otrebla** [comment]
@GladeDiviney thank you for the support. Going to try what you suggested.

**Comment by GladeDiviney** [comment]
The [jprint sample](https://github.com/HPInc/jipp/blob/master/sample/jprint/src/main/java/sample/Main.java) now does everything mentioned in the comment above, enjoy!
