### ISSUE TITLE
Unsupported-attributes

### ISSUE THREAD

**Issue by wrss2** [HPInc/jipp#73]
I getting error of unsupported-attributes with example 

            IppPacket printRequest = new IppPacket(Operation.printJob, 1,  
                       groupOf(operationAttributes,
                            attributesCharset.of("utf-8"),
                            attributesNaturalLanguage.of("en"),
                            printerUri.of(uri),
                            requestingUserName.of("jprint"),
                            documentFormat.of("image/jpeg")
                        ),         
                        groupOf(jobAttributes,
                            media.of("isoA5_148x210"),
                            printQuality.of(quality)                            
                        )
            );

and i have question what is proper way to putt all important job atributes like: print quality, resolution, page size a5, a4 etc. I try with media.of("isoA5_148x210"), and media.of("iso_a5_148x210") but still that same unsupported-attributes.

And other question its ther way to put  information for pritner without groupOf like int this example below

            var file = {
                "operation-attributes-tag":{
                    "requesting-user-name": "User",
                    "job-name": "Print Job",
                    "document-format": "image/jpeg", // jpeg/png
                },
                "job-attributes-tag": {
                    "media": "iso_a5_148x210mm",
                    "print-quality": "high",
                    "orientation-requested":"portrait"
                },
                version: "2.0",
                data: fileBuffer
            };

or style like from ippTool like down below:

        Print a test page using print-job
        {
	The name of the test...
	NAME "Print file using Print-Job"

	The operation to use
	OPERATION Print-Job

	Attributes, starting in the operation group...
	GROUP operation-attributes-tag
	ATTR charset attributes-charset utf-8
	ATTR language attributes-natural-language en
	ATTR uri printer-uri $uri
	ATTR name requesting-user-name $user
	ATTR mimetype document-format image/jpeg
	
	GROUP job-attributes-tag
	ATTR integer copies 1
	ATTR name media iso_a5_148x210mm
	ATTR enum print-quality 4
	ATTR collection media-col {
	 US Letter plain paper from the "main" tray
		MEMBER collection media-size {
	        MEMBER integer x-dimension 14800
		  MEMBER integer y-dimension 21000
		}
		MEMBER keyword media-source "main"
		MEMBER keyword media-type "stationery"
	}

	FILE $filename

	What statuses are OK?
	STATUS successful-ok
	STATUS successful-ok-ignored-or-substituted-attributes

	What attributes do we expect?
	EXPECT job-id
	EXPECT job-uri
       }

**Comment by GladeDiviney** [comment]
> I try with media.of("isoA5_148x210"), and media.of("iso_a5_148x210") but still that same unsupported-attributes.

Neither of those are valid Media keywords, see https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xhtml. Use `Media.isoA5_148x210mm`.

For other attributes there's a huge library of defined keywords, enums, etc. See the documentation for each attribute type, e.g. `Types.printQuality`.

Java APIs and types are used to construct the IPP packet, a simple JSON-like format is not sufficient to encode a valid packet. The `ipptool` format parses packet content from text and is is currently not supported.

**Comment by wrss2** [comment]
Well i getting error i Java with using this Media.isoA5_148x210mm.

**Comment by GladeDiviney** [comment]
https://github.com/HPInc/jipp/search?q=isoA5_148x210mm&unscoped_q=isoA5_148x210mm

**Comment by wrss2** [comment]
so why this is not working?

**Comment by GladeDiviney** [comment]
The Java you are looking for is:

```java
Types.media.of(Media.isoA5_148x210mm),
```

JIPP expresses the IANA types in bumpyCase so `-` and `_` are removed wherever possible. But  `_` is preserved when necessary separate numerics.

**Comment by wrss2** [comment]
Hmm now i know why is not working import com.hp.jipp.model.Media; dont import this  Ha
