### ISSUE TITLE
Problem with margins

### ISSUE THREAD

**Issue by wrss2** [HPInc/jipp#74]
I have this sample of configuration:

                MediaCol.MediaSize mediaSize = new MediaCol.MediaSize(14800,21000);
                MediaCol mediaType1 = new MediaCol();
                mediaType1.setMediaLeftMargin(0);
                mediaType1.setMediaRightMargin(0);
                mediaType1.setMediaBottomMargin(0);
                mediaType1.setMediaSize(mediaSize);
                mediaType1.setMediaTopMargin(0);
                mediaType1.setMediaType(new KeywordOrName(MediaType.photographic));

                List<MediaCol> readyList = new ArrayList<>();
                readyList.add(mediaType1);
                IppPacket printRequest = new IppPacket(Operation.printJob, 1,
                        groupOf(operationAttributes,
                                attributesCharset.of("utf-8"),
                                attributesNaturalLanguage.of("en"),
                                printerUri.of(uri),
                                requestingUserName.of("jprint"),
                                documentFormat.of("image/jpeg")
                        ),
                        groupOf(jobAttributes,
                                Types.mediaCol.of(mediaType1),
                                Types.printScaling.of(scaling),
                                Types.printerKind.of(kind),
                                Types.media.of(Media.isoA5_148x210mm),
                                Types.printQuality.of(Integer.valueOf(quality))
                        )
                );

And if i print with scaling "fit" or "fill" i geting 4-8 mm margins.

**Comment by GladeDiviney** [comment]
Do you have a question about JIPP behavior?

**Comment by wrss2** [comment]
Yes i have i have non zero margins and i putt margins to 0 why?

**Comment by GladeDiviney** [comment]
I don't know, perhaps the printer doesn't support it.

**Comment by wrss2** [comment]
Margins is supported. How to enable 0 margins when i have scaling in fit or fill?


        "media-type-supported": [
            "photographic",
            "stationery"
        ],
        "media-source-supported": [
            "auto",
            "main"
        ],
        "media-top-margin-supported": [
            0,
            500
        ],
        "media-left-margin-supported": [
            0,
            340,
            640
        ],
        "media-right-margin-supported": [
            0,
            340,
            630
        ],
        "media-bottom-margin-supported": [
            0,
            500

**Comment by wrss2** [comment]
I`am getting 

:   unsupported-attributes {
01-30 19:57:03.473 31177 31443 I PRINTER_IPP:     media-col =
01-30 19:57:03.473 31177 31443 I PRINTER_IPP:       {
01-30 19:57:03.473 31177 31443 I PRINTER_IPP:         media-bottom-margin = 0,
01-30 19:57:03.473 31177 31443 I PRINTER_IPP:         media-left-margin = 0,
01-30 19:57:03.473 31177 31443 I PRINTER_IPP:         media-right-margin = 0,
01-30 19:57:03.473 31177 31443 I PRINTER_IPP:         media-size = { x-dimension = 14800, y-dimension = 21000 },
01-30 19:57:03.473 31177 31443 I PRINTER_IPP:         media-top-margin = 0,
01-30 19:57:03.473 31177 31443 I PRINTER_IPP:         media-type = photographic } },

**Comment by wrss2** [comment]
How to set media-size with x and y ? With this i getting unsuported attribute?       

MediaCol.MediaSize mediaSize = new MediaCol.MediaSize(14800,21000);
            MediaCol mediaType1 = new MediaCol();
            mediaType1.setMediaLeftMargin(0);
            mediaType1.setMediaRightMargin(0);
            mediaType1.setMediaBottomMargin(0);
            mediaType1.setMediaSize(mediaSize);
            mediaType1.setMediaTopMargin(0);
            mediaType1.setMediaType(new KeywordOrName(MediaType.photographic));

**Comment by GladeDiviney** [comment]
You can use `MediaSizes.parse(Media.isoA5_148x210mm)` to extract a `MediaCol.MediaSize`.

But your definition looks fine. The printer probably doesn't support A5 borderless. You can check its full `media-col-database` to be sure.

**Comment by wrss2** [comment]
I have othe  problem on A4  0 margins works but on A5 not i geting still  4-8 mm margins please ehlp to to adjust this margins some example code.
