### ISSUE TITLE
Media size

### ISSUE THREAD

**Issue by wrss2** [HPInc/jipp#75]
How to set media-size with x and y ? With this code bellow i getting unsuported attribute?

MediaCol.MediaSize mediaSize = new MediaCol.MediaSize(14800,21000);
MediaCol mediaType1 = new MediaCol();
mediaType1.setMediaLeftMargin(0);
mediaType1.setMediaRightMargin(0);
mediaType1.setMediaBottomMargin(0);
mediaType1.setMediaSize(mediaSize);
mediaType1.setMediaTopMargin(0);
mediaType1.setMediaType(new KeywordOrName(MediaType.photographic));

**Comment by GladeDiviney** [comment]
Your code is correct. As in #74, your printer is reporting that this combination of media-col settings is not supported.

I have extended `jprint` to help demonstrate how you can query and list available printer settings. Try (from latest master) `jprint -g -d ipp:/192.168.0.100/ipp/print` to list out all printer attributes including `media-col-database`, or browse the code at https://github.com/HPInc/jipp/blob/master/sample/jprint/src/main/java/sample/Main.java#L79.

**Comment by wrss2** [comment]
I dont get  deep sethings of printer i`m  geting strange info. I have in spec  that pritner  have dpi 9600x2400 but in ipp i get 600x600 hmm what  manufacture just lie about dpi or what?

**Comment by GladeDiviney** [comment]
Sorry, I can only provide support for issues with JIPP. I can only accept suggestions, comments, or questions that directly concern JIPP.
