### ISSUE TITLE
Qestion: how to get resolution of Color

### ISSUE THREAD

**Issue by wrss2** [HPInc/jipp#76]
My printer  send mi info about only resolution in black 600x600 but i know that is another resolution in color how to get it and how to set it? My rpitner have 600x600 dpi in black nad 9600x2400 in color 1pl

**Comment by GladeDiviney** [comment]
Hi @wrss2 I'm glad you are using JIPP but this is not a printer support forum. Please limit any submitted questions here to specific JIPP capabilities. In the meantime you can refer to the IPP specifications themselves to learn more about how IPP printing works.
