### ISSUE TITLE
Consider attributes-charset for encoding and decoding of strings

### ISSUE THREAD

**Issue by gmuth** [HPInc/jipp#78]
Shouldn't the `attributes-charset` be considered when encoding and decoding bytes to characters/strings or vice versa? I think you should not assume other ipp protocol components support the [operating system dependent default character encoding of the jvm](https://www.baeldung.com/java-char-encoding) (e.g. windows-1252).

**Comment by GladeDiviney** [comment]
The default character encoding of the JVM should not have any effect, all strings are being interpreted and written as UTF-8.

Also, UTF-8 support is required for both clients and printers.

However, it is true that strings *ought* to be encoded/decoded using `attributes-charset`. Is there any implementation that does not use UTF-8?

(See also https://github.com/HPInc/jipp/issues/77#issuecomment-602116274)

**Comment by gmuth** [comment]
I was confused by `readString() = String(readValueBytes())` and thought this would use the jvm default Charset. I now learned that kotlin String(bytes) is different to java String(bytes) and uses a system independent charset (=UTF8).

My interpretation of rfc 8010 3.9 is that values MUST be encoded in US-ASCII for tags charset, naturalLanguage, mimeMediaType, keyword, uri and uriScheme. As of rfc 8011 4.1.4.1 name and text values MUST be encoded or decoded with the charset defined in "attributes-charset".

**Comment by GladeDiviney** [comment]
There are complexity costs to maintaining and applying the attributes-charset value to all string encoding/decoding. So it will help me prioritize this work if you or someone else can provide any data on real-world applications that do not use UTF-8. Without this it will be unlikely to happen.

Yes, it is possible to provide impermissible characters when encoding/decoding `natural-language` and other items that strictly require US-ASCII. JIPP does not enforce these limits, but perhaps it could. Seems like a separate issue though.

**Comment by gmuth** [comment]
I agree. This issue is not a bug report and therefore does not need any further action. It's likely that using UTF-8 is more tolerant when implementors do not limit the charset to US-ASCII as specified for some tags but use UTF-8 instead.

**Comment by GladeDiviney** [comment]
OK, I'll close for now, but thanks for bringing this up. For the record, I think we could support this feature if it was ever needed.
